# numpy入门

In [8]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print(array)
print('维度:',array.ndim)
print('形状:',array.shape)
print('元素数:',array.size)

[[1 2 3]
 [4 5 6]]
维度: 2
形状: (2, 3)
元素数: 6


# numpy创建array

In [9]:
import numpy as np
#定义属性dtype
#定义形状reshape
#定义初始矩阵得值 empty/zeros/ones  方法((2,3))
#生成矩阵array()
#生成数列arange()
#生成线段linespace()


array = np.array([2,23,4],dtype = np.int)
print(array)
print(array.dtype)                #返回定义array的属性

array1 = np.array([[2,23,4],[4,5,6]])     #定义二维矩阵 用[]包括
print(array1)


array2 = np.zeros((3,4))   #生成三排四列 值为0的矩阵
print(array2)

array3 = np.ones((3,4))    # 值为1
print(array3)
 
a = np.arange(0,10,2)   #生成一个0-10 步长为2的数组
print(a)

a1 = np.arange(12).reshape((3,4))  #生成0-12的 形状为3,4的矩阵
print(a1)

a2 = np.linspace(1,10,5)    #生成1-10的 分5段 的数列
print(a2)


[ 2 23  4]
int32
[[ 2 23  4]
 [ 4  5  6]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[0 2 4 6 8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[  1.     3.25   5.5    7.75  10.  ]


# numpy的基本运算1

In [10]:
import numpy as np

# #一维数组:
a = np.arange(4)
b = np.array([10,20,30,40])

# #必须是一一对应运算
# c = a+b 
# c = a*b     
# # c = b**a   #乘方运算
# # c = np.sin(a)  #三角函数运算

# print(a)
# print(a<3)    #布尔值返回判断结果
# print(b)
# print(c)
# print(np.dot(a,b))    #一维数组的dot ，np.dot([1,2,3],[4,5,6]) = 1*4 + 2*5 + 3*6  = 32


#二维矩阵:
a = np.arange(4).reshape((2,2))
b = np.array([[10,20],[30,40]])

c = a*b   #基础运算
c_dot = np.dot(a,b)   #二维矩阵的dot 

print(a)
print(b)
print(c)
print(c_dot)


[[0 1]
 [2 3]]
[[10 20]
 [30 40]]
[[  0  20]
 [ 60 120]]
[[ 30  40]
 [110 160]]


# numpy的基本运算2

In [11]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print(array)
print('最小值索引:',np.argmin(array))
print('最大值索引:',np.argmax(array))
print('平均值:',np.mean(array))
#扩展:
print('平均值的属性:',np.mean(array,axis=0))      #axis=0对列进行平均值计算,axis=1对行进行平均值计算
print('中位数:',np.median(array))
print('累加:',np.cumsum(array))                  #输出一维矩阵 
print('累差:',np.diff(array))                    #输出二维矩阵
print('得到非零数的位置:',np.nonzero(array))      #输出行矩阵,列矩阵
print('排序:',np.sort(array))                    #逐行排序
print('矩阵转置:',np.transpose(array))           #行列转换
print('矩阵运算中的转置:',(array.T).dot(array))
print('滤波:',np.clip(array,2,5))                #最小值为2,最大值5 


[[1 2 3]
 [4 5 6]]
最小值索引: 0
最大值索引: 5
平均值: 3.5
平均值的属性: [ 2.5  3.5  4.5]
中位数: 3.5
累加: [ 1  3  6 10 15 21]
累差: [[1 1]
 [1 1]]
得到非零数的位置: (array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))
排序: [[1 2 3]
 [4 5 6]]
矩阵转置: [[1 4]
 [2 5]
 [3 6]]
矩阵运算中的转置: [[17 22 27]
 [22 29 36]
 [27 36 45]]
滤波: [[2 2 3]
 [4 5 5]]


# numpy的索引

In [12]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print(array)
print('行索引:',array[1])
print('列索引:',array[:,1])
print('行列索引:',array[1][1])
print('另一种写法:',array[1,1])

for row in array:
    print(row)     #迭代每一行

for column in array.T:
    print(column)  #迭代每一列

print(array.flatten()) #返回一个序列
for item in array.flat:#迭代每一个值
    print(item)



[[1 2 3]
 [4 5 6]]
行索引: [4 5 6]
列索引: [2 5]
行列索引: 5
另一种写法: 5
[1 2 3]
[4 5 6]
[1 4]
[2 5]
[3 6]
[1 2 3 4 5 6]
1
2
3
4
5
6


# numpy的合并

In [13]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2,2,2])


# print(np.vstack((a,b)))  #上下合并
# print(np.hstack((a,b)))  #左右合并
# #添加一个维度:         #也可以直接reshape
# print(a.shape)
# print(a[:,np.newaxis])# 在纵向加一个维度
# print(a[np.newaxis,:])# 在横向加一个维度
# print(a[:,np.newaxis].shape)

#综合
a = np.array([1,1,1])[:,np.newaxis]  
b = np.array([2,2,2])[:,np.newaxis]  # 产生竖向矩阵
print(a)
print(b)
c = np.concatenate((a,b,a),axis=1)   #axis=1横向合并
print(c)


[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]
[[1 2 1]
 [1 2 1]
 [1 2 1]]


# numpy的分割

In [14]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)

print(np.split(a,2,axis=1)) #等量 横向分割成2块
print(np.array_split(a,3,axis=1)) #不等量 横向分割成3块

#也可以用:
# print(np.vsplit(a,3)) #上下分成3行
# print(np.hsplit(a,2)) #左右分成2列


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


# numpy的赋值

In [ ]:
import numpy as np
a = np.arange(4)
print(a)

#赋值:  b,c,d 完完全全一样,改变一个全部改变.
# b=a
# c=a
# d=b
# print(a,b,c,d)

#或者：
# f = a[:]

#copy :  b 只得到copy时的值,不会具有后续的关联性
b = a.copy() #deepcopy()

a[2] = 11
print(a[2],b[2])
